raidengine/raidengine.go
=> Added movement result struct

command/command.go, raidengine/raidengine.go
- [Added error for bad config](https://github.com/privateerproj/privateer-sdk/commit/8477e831d7d21936bccf2cc243d553ac20f8577e)
- [Modified 'strikes' to 'armory' for better log+strike+control handling](https://github.com/privateerproj/privateer-sdk/commit/08ea198d1c6cfbd288e1dd2ba3481f52e64483af)
- [Added default write path: ~/privateer/logs/DATETIME](https://github.com/privateerproj/privateer-sdk/pull/7/commits/11f516175b462c29e6aa1111d9780c41ee69d2c8) (fixes https://github.com/privateerproj/privateer/issues/18)
=> [Fix] Correcting unexpected behaviors in plugin execution

raidengine/output.go, raidengine/raidengine.go
Also added some minor logging improvements
=> Adjusted to use Tactic naming convention more prominently in the code

raidengine/raidengine.go
Also corrected a nearby residual naming convention
Example usage:
```go
var Endpoint string
func (a *ABS) Initialize() error {
Endpoint = viper.GetString("raids.ABS.endpoint")
if Endpoint == "" {
return fmt.Errorf("raids.ABS.endpoint is required")
}
return nil
}
```
=> Added Initialize method to Armory

utils/utils.go, utils/utils_test.go
Also commented out `TestCallerFileLine` because it's being a punk
=> Added utilities for required variables

raidengine/change.go, raidengine/change_test.go
Draft: Currently includes commits from #21
=> Added change management struct

.github/workflows/ci.yml, .gitignore, raidengine/output.go, raidengine/raidengine.go, raidengine/raidengine_test.go, raidengine/strike.go, raidengine/tactic.go, raidengine/tactic_test.go
summary notes:
- The Run function has reduced complexity by delegating specific operations to helper functions
- The Tactic struct and its execution logic were extracted into a new tactic.go file, further modularizing the codebase
- New tests added for Run and runTactic, including edge cases like missing tactics in the configuration
- The introduction of a testArmory mock makes testing easier by simulating the behavior of the Armory interface
- Reduced complexity of condition for multiple and single tactics
- The tests now cover cases like multiple tactics, failed tactics, and missing configurations
=> Refactored tactics handling, and added unit tests

raidengine/change.go, raidengine/change_test.go, raidengine/raidengine.go, raidengine/raidengine_test.go, raidengine/strike.go, raidengine/tactic.go, raidengine/tactic_test.go
- changed applyFunc and changeFunc to private because those tippedAdde over when marshaling
- added slice of change objects to the Movement struct
- added strikeResult.Finalize() to set messages + revert changes from all movements in the strike
- added badStateAlert to strikeResult
- added logic to halt subsequent strikes and tactics if badStateAlert is true
- almost died writing these unit tests
=> added change reversion and bad state check

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/scorecard.yml, CODEOWNERS
- immutables will use tags, mutable will use SHAs
- minor/patch updates will be one PR
- major updates will be individual PRs to ensure they are more "visible"
=> chore: add dependabot config and update actions

config/config.go
Reverts privateerproj/privateer-sdk#34
=> fix: revert PR #34

.github/workflows/ci.yml, pluginkit/test.go, pluginkit/test_test.go
Added two new methods to TestResult based on user feedback
=> feat: new pass and fail fields for TestResult

.github/release-drafter.yml, .github/workflows/auto-labeler.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml
=> feat: add release, auto labeler, pr-title reusable github actions

.github/release-drafter.yml
Relates to https://github.com/privateerproj/privateer/pull/78
=> ci: bug fixes should update semver patch not minor

.github/release-drafter.yml, .github/workflows/auto-labeler.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml
mainly `feature` was missing from the minor semver section.  If it's able to trigger a release it should trigger a semver minor change.
=> ci: update labels that trigger semver changes

LICENSE
Copied from https://choosealicense.com/licenses/apache-2.0/
=> chore: add Apache 2.0 license to project

pluginkit/test_set.go, pluginkit/test_set_test.go, pluginkit/vessel.go
=> fix: Use a runtime config pointer for ExecuteInvasiveTests

config/config.go, config/config_test.go
This pull request includes changes to the `config/config.go` and `config/config_test.go` files to enhance the handling of configuration variables and improve test coverage. The most important changes include modifying how local and global variables are merged, simplifying the missing variables check, and adding new test cases.
Enhancements to variable handling:
* [`config/config.go`](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L48-R54): Modified the merging logic to ensure local variables overwrite or add to global variables and added logging for the merged variables.
* [`config/config.go`](diffhunk://#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17L91-R95): Simplified the logic for checking missing required variables by iterating …
=> fix: combos of top and service level vars now work

.github/workflows/ci.yml, go.mod, go.sum, pluginkit/evaluation_suite.go, pluginkit/test_data.go, utils/utils.go
- Updates to support changes in sci repo
- Updated version to v0.3.1 in anticipation of the next release being cut with the changes PR-ed there
=> feat: Support new SCI assessment change functionality

pluginkit/evaluation_orchestrator.go, pluginkit/evaluation_orchestrator_test.go, pluginkit/evaluation_suite.go, pluginkit/evaluation_suite_test.go
This fixes a sad oversight in field names, where we solved for yaml clarity through snake case instead of using yaml tags
=> fix: field names to pascal-case with yaml tags for snake-case

.github/CODEOWNERS
so we get auto added to new PRs
=> fix: CODEOWNERS oss team

Makefile, config/config.go, go.mod, go.sum, pluginkit/evaluation_orchestrator.go, pluginkit/evaluation_orchestrator_test.go, pluginkit/evaluation_suite.go, pluginkit/evaluation_suite_test.go
Using Gemara v0.10.1 and a local version of `revanite-io/pvtr-github-repo` that imports this branch, I've managed to produce SARIF that passes checks from the [official validator](https://sarifweb.azurewebsites.net/Validation).
This one has been tough to get completely polished, but it seems to be working as expected.
=> feat: Add support for SARIF output format
