- raidengine/raidengine.go
Follows #3.
The config may now stipulate a single `tactic` string or a list of strings in `tactics`. Tactics will supersede tactic. 
Output will now be sorted according to the tactic used:
If a strike falls under multiple tactics, the `ControlID` for the active tactic will be logged.
Enabling this required moving quite a bit of logic out of the wireframe to keep everything cohesive— so that's a side benefit. Previous versions of the wireframe will break with this change.
> Add support for lists of tactics

- raidengine/raidengine.go
Failures were getting counted as successes. This inverts that logic but keeps failure counts.
> count successes and failues

- raidengine/raidengine.go
Replaces the following repetitive raid code: 
```go
CCC_C01_TR01_T01_Result := CCC_C01_TR01_T01()
result.Movements["CCC_C01_TR01_T01"] = CCC_C01_TR01_T01_Result
if !CCC_C01_TR01_T01_Result.Passed {
result.Message = CCC_C01_TR01_T01_Result.Message
return
}
```
with the updated:
```go
raidengine.ExecuteMovement(&result, CCC_C01_TR01_T01)
```
> Added common logic for running a movement

- raidengine/raidengine.go
This solves for the following problem:
```yaml
CCC_C01_TR01:
passed: true
description: The service enforces the use of secure transport protocols for all network communications (e.g., TLS 1.2 or higher).
message: Strike has not yet started.
docsurl: https://maintainer.com/docs/raids/ABS
controlid: CCC.C01
movements:
CCC_C01_TR01_T01:
passed: true
description: Checking TLS version of response
message: TLS 1.3 is being used
function: github.com/privateerproj/privateer-pack-ABS/armory.CCC_C01_TR01_T01
value: null
```
> Update Strike Result Regardless

- .github/workflows/ci.yml
- raidengine/raidengine.go
- raidengine/raidengine_test.go
- Added condition for failed movements to ExecuteMovement
- Added unit test for ExecuteMovement
tertiary: fixed malfunctioning CI pipeline so that checks will actually run
> Fix: Failed strikes should always fail movement

- config/config.go
- raidengine/tactic_test.go
- raidengine/vessel.go
- raidengine/vessel_test.go
Also moved `StockArmory` into `Mobilize` since it will always/only be called in that sequence
> Fix: Added passthrough for raid required variables

- .github/workflows/pr-title.yml
we're going to start implementing [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for PR titles to help maintainers get a quick view into what the PR is for
> feat: add pr title validation

- raidengine/tactic_test.go
- raidengine/vessel.go
- raidengine/vessel_test.go
This pull request includes changes to the `raidengine` package to refactor how the `Armory` and `RequiredVars` are handled in the `Vessel` struct. The most important changes include modifying the `Vessel` struct to directly include the `Armory` and `RequiredVars` fields, updating the `StockArmory` and `Mobilize` methods accordingly, and adjusting the associated tests.
> feat: changed vessel to use fields instead of args

- raidengine/vessel.go
This will allow for the nesting of a custom behavior that will execute _after_ the config is initialized and _before_ the tactics begin.
The most likely outcome of a custom initializer would be to set global variable content in the config vars that strikes can access via `Armory.Config`
> feat: added optional Initializer func to vessel

- command/command.go
- config/config.go
- plugin/plugin.go
- plugin/serve.go
- pluginkit/armory.go
- pluginkit/change.go
- pluginkit/change_test.go
- pluginkit/movement.go
- pluginkit/strike.go
- pluginkit/strike_test.go
- pluginkit/tactic.go
- pluginkit/tactic_test.go
- pluginkit/vessel.go
- pluginkit/vessel_test.go
This pull request includes significant changes to rename and refactor the codebase from using the term "raid" to "plugin". The changes affect various files and identifiers to reflect this new terminology.
> feat: rename raid to plugin

- .github/workflows/ci.yml
- command/command.go
- config/config.go
- pluginkit/vessel.go
resolves https://github.com/privateerproj/privateer/issues/66
> feat: added flag to disable file outputs

- command/command.go
- config/config.go
- pluginkit/vessel.go
I tested this inside the generated plugin and also from the core level.  Having the CORRECT config is the fix.  Not a code change.
Example new output of config trace:
```yaml
logLevel: trace
write-directory: test_output
services:
my-cloud-services1:
plugin: example
test-suites:
- tlp_green
- tlp_clear
```
```bash
➜  privateer git:(main) ✗ ./privateer run
2025-01-19T03:56:45.775-0600 [TRACE] Creating a new config instance for service: serviceName=overview loglevel=trace write-directory=/Users/jmeridth/.privateer/logs/2025-01-19T035645-0600 invasive=false test-suites=[] vars=map[] writing output to file=true
```
```bash
➜  privateer git:(main) ✗ ./privateer run --service my-cloud-services1
2025-01-19T04:01:44.149-0600 [TRACE] Creating a new config instance for service: …
```
> chore: revert ReadConfig function

- command/command.go
- config/config.go
- config/config_test.go
- pluginkit/armory.go
- pluginkit/change.go
- pluginkit/test.go
- pluginkit/test_set.go
- pluginkit/test_suite.go
- pluginkit/vessel.go
- ensure only json and yaml are output types allowed
comment out test proving `write` config option defaults to `true` when not present.  This is set by cobra and we currently don't include cobra setup in our `config_test.go`.  Will do quick follow PR for this.  Want this PR merged so we can have both `output` (json|yaml) and `write` (on|off).
<details><summary>Existing stdout YAML output example</summary>
<p>
```yaml
2025-01-20T13:44:38.975-0600 [TRACE] Creating a new config instance for service: serviceName=my-cloud-service1 loglevel=trace write=true write-directory=/Users/jmeridth/.privateer/logs/2025-01-20T134438-0600 invasive=false test-suites=["tlp_red"] vars=map[] output=yaml
2025-01-20T13:44:38.975-0600 [ERROR] CCC.C01: testSet did not return a result, and may still be under …
```
> feat: designate output type

- pluginkit/vessel.go
This PR ensures that bad states are recorded for logging in the same fashion as everything else.
After we merge this, I'd like to ask @sarahecraddock to confirm this resolves everything from #62.
> fix: bad states not getting written to log

- go.mod
- go.sum
- pluginkit/evaluation_suite.go
- pluginkit/test_data.go
- pluginkit/vessel_test.go
Most of this work was done in the latest SCI release. This applies that upgrade and adds testing capability to ensure our execute function works properly when using the `invasive` config var.
> fix: invasive config var will now prevent change.Apply() in plugins

- go.mod
- go.sum
- pluginkit/evaluation_suite.go
- pluginkit/vessel.go
This change is being made as gopkg.in/yaml.v3 is no longer maintained.
> chore: replace gopkg.in/yaml.v3 with github.com/goccy/go-yaml

- go.mod
- go.sum
- pluginkit/evaluation_orchestrator.go
- pluginkit/evaluation_orchestrator_test.go
- pluginkit/evaluation_suite.go
- pluginkit/evaluation_suite_test.go
- pluginkit/test_data.go
This PR updates our dependency to reflect the move of sci to the ossf and the rename to gemara
> chore: use gemara v0.3.10 in place of sci

- .github/workflows/ci.yml
- .github/workflows/lint.yml
This PR adds security configuration to GitHub Actions workflows by setting persist-credentials: false for checkout actions. This prevents GitHub credentials from being persisted in the Git configuration after repository checkout, reducing potential security risks from credential exposure.
- Added persist-credentials: false to all actions/checkout@v5 steps across multiple workflow files
- Ensures credentials are not available to subsequent steps that don't explicitly need them
- Maintains existing workflow functionality while improving security posture
> fix: ensure we're not persisting credentials after checkouts

- .github/dependabot.yml
Update dependabot to not add labels to its PRs. It is colliding with our auto labeller and releases.
> fix(ci): Update dependabot.yml

- config/config.go
This commit sanitizes the vars during logging because vars used for authn creds are commonly provided
As an example, pvtr-github-repo, when run on the latest release, emits:
```
Using vars: map[owner:revanite-io repo:example-osps-baseline-level-1 token:gho_.......]
```
and, with this change, it will emit:
```
Using vars: map[owner:revanite-io repo:example-osps-baseline-level-1 token:REDACTED]
```
> fix: logging of authn/credential vars
